import { FunctionComponent } from "react";

import {
  ArrowDownToLine,
  ArrowRight,
  Bell,
  Bolt,
  Box,
  Calendar,
  ChartColumnIncreasing,
  Check,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleX,
  CloudUpload,
  Copy,
  Download,
  EllipsisVertical,
  Eye,
  Facebook,
  Hammer,
  Image,
  Info,
  Instagram,
  Layers,
  LayoutList,
  Link,
  Link2,
  ListChecks,
  Loader,
  Lock,
  MonitorCog,
  MoreHorizontal,
  Music2,
  Package,
  Palette,
  Pencil,
  Percent,
  PlugZap,
  Plus,
  QrCode,
  RefreshCw,
  ScanLine,
  Search,
  Share,
  Shield,
  Sparkles,
  Square,
  Squircle,
  Store,
  Tag,
  Trash,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  User,
  Utensils,
  Wallet,
  Wifi,
  X,
} from "lucide-react";

import Logo from "../assets/icons/logo.svg?react";

export const iconListComponents = {
  box: Box,
  eye: Eye,
  bolt: Bolt,
  logo: Logo,
  shop: Store,
  check: Check,
  share: Share,
  trash: Trash,
  loader: Loader,
  "monitor-cog": MonitorCog,
  plus: Plus,
  tag: Tag,
  search: Search,
  pencil: Pencil,
  package: Package,
  "ellipsis-vertical": EllipsisVertical,
  "more-horizontal": MoreHorizontal,
  layers: Layers,
  "layout-list": LayoutList,
  "alert-circle": CircleAlert,
  "chevron-down": ChevronDown,
  "cloud-upload": CloudUpload,
  "chart-column-increasing": ChartColumnIncreasing,
  calendar: Calendar,
  hammer: Hammer,
  wallet: Wallet,
  percent: Percent,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  palette: Palette,
  image: Image,
  "scan-line": ScanLine,
  instagram: Instagram,
  facebook: Facebook,
  "music-2": Music2,
  wifi: Wifi,
  lock: Lock,
  "trash-2": Trash2,
  x: X,
  user: User,
  bell: Bell,
  shield: Shield,
  "arrow-down-to-line": ArrowDownToLine,
  "arrow-right": ArrowRight,
  "link-2": Link2,
  link: Link,
  info: Info,
  "plug-zap": PlugZap,
  "chevron-right": ChevronRight,
  "list-checks": ListChecks,
  "circle-check": CircleCheck,
  "circle-dot": CircleDot,
  "circle-x": CircleX,
  sparkles: Sparkles,
  utensils: Utensils,
  "qr-code": QrCode,
  square: Square,
  squircle: Squircle,
  upload: Upload,
  download: Download,
  "refresh-cw": RefreshCw,
  copy: Copy,
} as const satisfies Record<string, FunctionComponent<React.RefAttributes<SVGSVGElement>>>;

export type IconNameTypes = keyof typeof iconListComponents;
