import { FunctionComponent } from "react";

import {
  Bolt,
  Box,
  Calendar,
  ChartColumnIncreasing,
  Check,
  ChevronDown,
  CircleAlert,
  CloudUpload,
  EllipsisVertical,
  Eye,
  Facebook,
  Hammer,
  Image,
  Instagram,
  Layers,
  LayoutList,
  Loader,
  Lock,
  MonitorCog,
  Music2,
  Package,
  Palette,
  Pencil,
  Percent,
  Plus,
  ScanLine,
  Search,
  Share,
  Store,
  Tag,
  Trash,
  Trash2,
  TrendingDown,
  TrendingUp,
  Wallet,
  Wifi,
  X,
} from "lucide-react";

import Logo from "../assets/icons/logo.svg?react";

export const iconListComponents = {
  box: Box,
  eye: Eye,
  bolt: Bolt,
  logo: Logo,
  shop: Store,
  check: Check,
  share: Share,
  trash: Trash,
  loader: Loader,
  "monitor-cog": MonitorCog,
  plus: Plus,
  tag: Tag,
  search: Search,
  pencil: Pencil,
  package: Package,
  "ellipsis-vertical": EllipsisVertical,
  layers: Layers,
  "layout-list": LayoutList,
  "alert-circle": CircleAlert,
  "chevron-down": ChevronDown,
  "cloud-upload": CloudUpload,
  "chart-column-increasing": ChartColumnIncreasing,
  calendar: Calendar,
  hammer: Hammer,
  wallet: Wallet,
  percent: Percent,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  palette: Palette,
  image: Image,
  "scan-line": ScanLine,
  instagram: Instagram,
  facebook: Facebook,
  "music-2": Music2,
  wifi: Wifi,
  lock: Lock,
  "trash-2": Trash2,
  x: X,
} as const satisfies Record<string, FunctionComponent<React.RefAttributes<SVGSVGElement>>>;

export type IconNameTypes = keyof typeof iconListComponents;
